### ISSUE TITLE
[SECURITY]: Secret in Repo

### ISSUE THREAD

**Issue by aerocyber** [DeveloperCandy/mailbotadvertisement2#1]
Hi, I have noticed that you have saved the token as key.env in your repo. This is a bad practice. Consider alternative methods like [https://opensourcelibs.com/lib/python-dotenv](https://opensourcelibs.com/lib/python-dotenv). Also, make sure you revoke the key as well.

**Comment by DeveloperCandy** [comment]
Hey there, I actually was a noob back then but before posting, I did make sure the key was changed, thx for the concern tho

**Comment by aerocyber** [comment]
Alright! I'll close the issue then!
